services:
  db:
    image: mysql:8.0
    container_name: banco_open
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: weslley03
      MYSQL_DATABASE: api-schema
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: application 
    ports: 
      - "3000:3000"  
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:weslley03@db:3306/api-schema
    command: >
      sh -c "npx prisma migrate deploy --schema=./src/infrastructure/prisma/schema.prisma && npm run start"  
  
volumes:
  db_data:
    driver: local